x-base-service: &base-service
  restart: unless-stopped

version: "3.9"

services:
  klipper:
    <<: *base-service
    container_name: klipper
    image: ghcr.io/whi-tw/klipper-docker/klipper:main
    privileged: true
    volumes:
      - /dev:/dev
      - gcode:/opt/gcode
      - /home/pi/printer_vars:/opt/vars

  moonraker:
    <<: *base-service
    container_name: moonraker
    image: ghcr.io/whi-tw/klipper-docker/moonraker:main
    depends_on:
      - klipper
      - traefik
    volumes:
      - moonraker-db:/opt/db
      - /var/run/docker.sock:/var/run/docker.sock:rw
    devices:
      - "/dev/gpiochip0:/dev/gpiochip0"
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.moonraker.loadbalancer.server.port=7125"
      - "traefik.http.routers.moonraker.rule=PathPrefix(`/websocket`,`/printer`,`/api`,`/access`,`/machine`,`/server`)"
      - "traefik.http.routers.moonraker.entrypoints=web"

  traefik:
    <<: *base-service
    image: traefik:v2.6
    container_name: traefik
    hostname: traefik
    command:
      - --accesslog
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
    ports:
      - "80:80"
    volumes:
        - "/var/run/docker.sock:/var/run/docker.sock:ro"

  fluidd:
    <<: *base-service
    image: cadriel/fluidd:latest
    container_name: fluidd
    depends_on:
      - moonraker
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.fluidd.loadbalancer.server.port=80"
      - "traefik.http.routers.fluidd.rule=PathPrefix(`/`)"
      - "traefik.http.routers.fluidd.entrypoints=web"

  ustreamer:
    <<: *base-service
    image: ghcr.io/whi-tw/klipper-docker/ustreamer:main
    container_name: ustreamer
    depends_on:
      - traefik
    devices:
      - /dev/video0:/dev/webcam
    command:
      - "--host=0.0.0.0"
      - "--port=8080"
      - "--slowdown"
      - "--device=/dev/webcam"
      - "--resolution=1280x960"
      - "--format=YUYV"
      - "--desired-fps=10"
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.ustreamer.loadbalancer.server.port=8080"
      - "traefik.http.routers.ustreamer.rule=PathPrefix(`/stream`)"
      - "traefik.http.routers.ustreamer.entrypoints=web"

volumes:
  gcode:
  moonraker-db:
