x-base-volumes: &base-volumes
  - run:/opt/run
  - gcode:/opt/gcode
  - log:/opt/log
  - /home/pi/printer_config:/opt/cfg

services:
  klipper:
    volumes: *base-volumes

volumes:
  run:
    driver_opts:
      type: tmpfs
      device: tmpfs
  gcode:
  log:
    driver_opts:
      type: tmpfs
      device: tmpfs
