name: "Image: klipper"

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "klipper/**"
      - ".github/workflows/klipper.yml"

jobs:
  build:
    uses: whi-tw/actions/.github/workflows/reusable-docker-build-basic-image.yml@main
    with:
      image_name: klipper
      dockerfile: ./klipper/Dockerfile
      build_context: ./klipper
      platforms: linux/arm64,linux/arm/v7
