---
name: Lint Code Base

on:
  push:
    branches-ignore:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    uses: whi-tw/actions/.github/workflows/reusable-superlinter.yml@main
