---
name: "Image: moonraker"

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "moonraker/**"
      - ".github/workflows/moonraker.yml"

jobs:
  build:
    uses: whi-tw/actions/.github/workflows/reusable-docker-build-basic-image.yml@main
    with:
      image_name: moonraker
      dockerfile: ./moonraker/Dockerfile
      build_context: ./moonraker
      platforms: linux/arm64,linux/arm/v7
