---
name: "Image: moonraker"

on:
  push:
    paths:
      - "moonraker/**"
      - ".github/workflows/moonraker.yml"
  pull_request:
    branches:
      - main
    paths:
      - "moonraker/**"
      - ".github/workflows/moonraker.yml"

jobs:
  build:
    uses: whi-tw/actions/.github/workflows/reusable-docker-build-basic-image.yml@main
    with:
      image_name: moonraker
      dockerfile: ./moonraker/Dockerfile
      build_context: ./moonraker
      platforms: linux/arm64,linux/arm/v7
      push: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
