name: "Image: moonraker"

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "moonraker/upstream/**"

jobs:
  build:
    uses: ./.github/workflows/build-image.yml
    with:
      app: moonraker
