name: "Image: moonraker"

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "moonraker/**"
      - ".github/workflows/moonraker.yml"
      - ".github/workflows/build-image-base.yml"

jobs:
  build:
    uses: ./.github/workflows/build-image-base.yml
    with:
      app: moonraker
