---
name: "Image: ustreamer"

on:
  push:
    paths:
      - "ustreamer/**"
      - ".github/workflows/ustreamer.yml"
  pull_request:
    branches:
      - main
    paths:
      - "ustreamer/**"
      - ".github/workflows/ustreamer.yml"

jobs:
  build:
    uses: whi-tw/actions/.github/workflows/reusable-docker-build-basic-image.yml@main
    with:
      image_name: ustreamer
      dockerfile: ./ustreamer/Dockerfile
      build_context: ./ustreamer
      platforms: linux/arm64,linux/arm/v7
      push: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
