name: "Image: ustreamer"

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "ustreamer/**"
      - ".github/workflows/ustreamer.yml"
      - ".github/workflows/build-image-base.yml"

jobs:
  build:
    uses: whi-tw/actions/.github/workflows/reusable-docker-build-basic-image.yml@69f1d5957b54951e648252fcd8342982999013fb
    with:
      image_name: ustreamer
      dockerfile: ./ustreamer/Dockerfile
      build_context: ./ustreamer
      platforms: linux/arm64,linux/arm/v7
